name: Ostad CI/CD Pipeline

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-late
  
    steps:
        - name: Install The nginx
          run: sudo apt install nginx -y

        - name: Checkout The Repo
          uses: actions/checkout@v4
        - name: Install Node js
          run: 
        - name: Start The Process
          run: pm2 start "npm run dev"

  setup-node:
    runs-on: self-hosted
    steps:
      - name: Setup Node 
        run: sudo apt update

